import { Octokit } from "@octokit/rest";
import { config } from "../config/env";

let octokit: Octokit | null = null;

function getOctokit(): Octokit {
  if (octokit) return octokit;
  octokit = new Octokit({ auth: config.github.token });
  return octokit;
}

export interface PrResult {
  id: number;
  url: string;
}

export async function createPullRequest(
  sourceBranch: string,
  ticketId: number,
  title: string,
  summary: string,
  filesChanged: string[]
): Promise<PrResult> {
  const gh = getOctokit();

  const fileList = filesChanged.map((f) => `- \`${f}\``).join("\n");
  const body = [
    `## Bug Fix for #${ticketId}`,
    "",
    `**${title}**`,
    "",
    "### Summary",
    summary,
    "",
    "### Files Changed",
    fileList,
    "",
    `### Azure DevOps`,
    `[Work Item #${ticketId}](${config.ado.orgUrl}/${encodeURIComponent(config.ado.project)}/_workitems/edit/${ticketId})`,
    "",
    "---",
    "*This PR was automatically generated by the AI Bug-Fix Bot.*",
  ].join("\n");

  const { data: pr } = await gh.pulls.create({
    owner: config.github.repoOwner,
    repo: config.github.repoName,
    head: sourceBranch,
    base: config.bot.repoBaseBranch,
    title: `fix: #${ticketId} - ${title}`,
    body,
  });

  return {
    id: pr.number,
    url: pr.html_url,
  };
}
